http:
  port: "8081"
    
process:
  host: "localhost"
  port: "8082"
  basePath: "/api"
  path:
    accounts: "/accounts"
  credentials:
    client_id: "![D+QUg+Smow4rs82rvLv5ws7giKJD5vtXDA086Va/pZfJqkBEFMHelw==]"
    client_secret: "![r5ldAwLZLOgNhgCQeIidkqZ/QWK8XaZwxtS+o+ZoabFHae2TEfwkgQ==]"
